// Import types from CmsGroupEditor
import type { FieldDef, CmsItem } from '../components/CmsGroupEditor'

export interface GroupConfig {
  title: string
  description: string
  apiKey: string
  accent?: string
  bgAccent?: string
  fields: FieldDef[]
  defaultItem: () => CmsItem
  maxItems?: number
  emptyMessage?: string
  previewField?: string        // field key to show as item title in list
  previewImageField?: string   // field key for thumbnail
  allowDuplicate?: boolean
}

// Registry: section slug → group slug → config
// section slugs match the route param in /admin/group/:section/:group
export const CMS_GROUPS: Record<string, Record<string, GroupConfig>> = {

  // ─── HOME ─────────────────────────────────────────────────────────────────
  'home': {

    'hero': {
      title: 'Hero Slides',
      description: 'Rotating hero banner slides shown at the very top of the homepage. Each slide has a headline, subtitle, buttons, and background.',
      apiKey: 'hero-scenes',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add your first hero slide to show on the homepage.',
      allowDuplicate: true,
      fields: [
        { key: 'title', label: 'Headline', type: 'text', placeholder: 'e.g. Building Tomorrow\'s Leaders' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', rows: 2, placeholder: 'Supporting text below the headline' },
        { key: 'buttonText', label: 'Primary Button Text', type: 'text', half: true, placeholder: 'e.g. Learn More' },
        { key: 'buttonUrl', label: 'Primary Button URL', type: 'url', half: true, placeholder: '/about-us' },
        { key: 'secondaryButtonText', label: 'Secondary Button Text', type: 'text', half: true, placeholder: 'e.g. Our Services' },
        { key: 'secondaryButtonUrl', label: 'Secondary Button URL', type: 'url', half: true, placeholder: '/business/technology' },
        { key: 'image', label: 'Background Image', type: 'image', folder: 'hero' },
        { key: 'videoUrl', label: 'Background Video (MP4, optional)', type: 'video', folder: 'hero' },
        { key: 'overlayOpacity', label: 'Overlay Opacity', type: 'select', half: true, options: [
          { value: '0', label: 'No overlay' },
          { value: '20', label: 'Light (20%)' },
          { value: '40', label: 'Medium (40%)' },
          { value: '60', label: 'Dark (60%)' },
          { value: '80', label: 'Very dark (80%)' },
        ]},
        { key: 'textAlign', label: 'Text Alignment', type: 'select', half: true, options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
          { value: 'right', label: 'Right' },
        ]},
      ],
      defaultItem: () => ({
        id: `slide-${Date.now()}`, enabled: true,
        title: '', subtitle: '', buttonText: 'Learn More', buttonUrl: '/',
        secondaryButtonText: '', secondaryButtonUrl: '',
        image: '', videoUrl: '', overlayOpacity: '40', textAlign: 'left',
      }),
    },

    'stats': {
      title: 'Statistics & Counters',
      description: 'Key numbers shown on the homepage — years of experience, countries served, employees, projects, etc.',
      apiKey: 'company',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'label',
      emptyMessage: 'Add statistics to showcase your company\'s impact.',
      fields: [
        { key: 'value', label: 'Value', type: 'text', half: true, placeholder: 'e.g. 15+' },
        { key: 'label', label: 'Label', type: 'text', half: true, placeholder: 'e.g. Countries Served' },
        { key: 'icon', label: 'Icon / Emoji', type: 'text', half: true, placeholder: 'e.g. 🌍 or Globe' },
        { key: 'description', label: 'Short Description', type: 'text', half: true, placeholder: 'Optional extra detail' },
      ],
      defaultItem: () => ({ id: `stat-${Date.now()}`, enabled: true, value: '', label: '', icon: '', description: '' }),
    },

    'testimonials': {
      title: 'Testimonials',
      description: 'Client reviews and testimonials shown in the homepage carousel.',
      apiKey: 'testimonials',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add client testimonials to build trust with visitors.',
      allowDuplicate: false,
      fields: [
        { key: 'name', label: 'Client Name', type: 'text', half: true, placeholder: 'e.g. John Smith' },
        { key: 'role', label: 'Job Title / Role', type: 'text', half: true, placeholder: 'e.g. CEO' },
        { key: 'company', label: 'Company Name', type: 'text', half: true, placeholder: 'e.g. Acme Corp' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. United Kingdom' },
        { key: 'review', label: 'Testimonial Text', type: 'textarea', rows: 4, placeholder: 'What they said about Yanabiya Group…' },
        { key: 'rating', label: 'Rating', type: 'select', half: true, options: [
          { value: '5', label: '★★★★★ (5)' },
          { value: '4', label: '★★★★ (4)' },
          { value: '3', label: '★★★ (3)' },
        ]},
        { key: 'image', label: 'Client Photo', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: `testimonial-${Date.now()}`, enabled: true, name: '', role: '', company: '', country: '', review: '', rating: '5', image: '' }),
    },

    'cta': {
      title: 'CTA Sections',
      description: 'Call-to-action blocks shown near the bottom of the homepage.',
      apiKey: 'cta-home',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'headline',
      emptyMessage: 'Add a call-to-action block to drive conversions.',
      maxItems: 2,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Ready to grow with Yanabiya?' },
        { key: 'subtext', label: 'Supporting Text', type: 'textarea', rows: 2, placeholder: 'A compelling reason to act…' },
        { key: 'primaryButtonText', label: 'Primary Button', type: 'text', half: true, placeholder: 'Get In Touch' },
        { key: 'primaryButtonUrl', label: 'Primary Button URL', type: 'url', half: true, placeholder: '/contact' },
        { key: 'secondaryButtonText', label: 'Secondary Button', type: 'text', half: true, placeholder: 'Our Services' },
        { key: 'secondaryButtonUrl', label: 'Secondary Button URL', type: 'url', half: true, placeholder: '/business' },
        { key: 'backgroundImage', label: 'Background Image', type: 'image', folder: 'misc' },
        { key: 'style', label: 'Style', type: 'select', half: true, options: [
          { value: 'dark', label: 'Dark (brand green)' },
          { value: 'light', label: 'Light' },
          { value: 'gradient', label: 'Gradient' },
        ]},
      ],
      defaultItem: () => ({ id: `cta-${Date.now()}`, enabled: true, headline: '', subtext: '', primaryButtonText: 'Get In Touch', primaryButtonUrl: '/contact', secondaryButtonText: '', secondaryButtonUrl: '', backgroundImage: '', style: 'dark' }),
    },

    'services-preview': {
      title: 'Services Preview — Homepage',
      description: 'Service cards shown on the homepage as a teaser. Controls which services appear and their order.',
      apiKey: 'home-services-preview',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add service preview cards to the homepage.',
      maxItems: 6,
      fields: [
        { key: 'title', label: 'Service Title', type: 'text', half: true, placeholder: 'e.g. Technology & IT' },
        { key: 'tagline', label: 'Tagline', type: 'text', half: true, placeholder: 'Short description shown on the card' },
        { key: 'image', label: 'Card Image', type: 'image', folder: 'services' },
        { key: 'link', label: 'Link URL', type: 'url', half: true, placeholder: '/business/technology' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: 'e.g. 💻' },
        { key: 'buttonText', label: 'Button Text', type: 'text', half: true, placeholder: 'Learn More' },
        { key: 'highlight', label: 'Highlight Badge', type: 'text', half: true, placeholder: 'e.g. New' },
      ],
      defaultItem: () => ({ id: `svc-prev-${Date.now()}`, enabled: true, title: '', tagline: '', image: '', link: '', icon: '', buttonText: 'Learn More', highlight: '' }),
    },

    'branch-preview': {
      title: 'Global Branches Preview — Homepage',
      description: 'Country/branch cards shown on the homepage as a teaser of the global presence section.',
      apiKey: 'home-branch-preview',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'country',
      previewImageField: 'image',
      emptyMessage: 'Add branch preview cards to the homepage.',
      maxItems: 6,
      fields: [
        { key: 'country', label: 'Country Name', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'countryCode', label: 'Country Code', type: 'text', half: true, placeholder: 'e.g. OM' },
        { key: 'flag', label: 'Flag Emoji', type: 'text', half: true, placeholder: '🇴🇲' },
        { key: 'tagline', label: 'Tagline', type: 'text', half: true, placeholder: 'e.g. Headquarters' },
        { key: 'image', label: 'Country/Office Image', type: 'image', folder: 'misc' },
        { key: 'link', label: 'Link URL', type: 'url', half: true, placeholder: '/country/om' },
        { key: 'description', label: 'Short Description', type: 'textarea', rows: 2 },
      ],
      defaultItem: () => ({ id: `branch-prev-${Date.now()}`, enabled: true, country: '', countryCode: '', flag: '', tagline: '', image: '', link: '', description: '' }),
    },

    'seo': {
      title: 'SEO Settings — Home',
      description: 'Controls how the homepage appears in Google search results and social media shares.',
      apiKey: 'seo-home',
      accent: 'text-sky-400',
      bgAccent: 'bg-sky-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'Yanabiya Group | Global Trading & Business Solutions' },
        { key: 'metaDescription', label: 'Meta Description (max 160 chars)', type: 'textarea', rows: 2, placeholder: 'Brief description for Google search results…' },
        { key: 'ogTitle', label: 'Social Share Title', type: 'text', half: true, placeholder: 'Leave blank to use Page Title' },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords (comma-separated)', type: 'tags', placeholder: 'Yanabiya, trading, Oman, global business' },
        { key: 'canonicalUrl', label: 'Canonical URL', type: 'url', half: true, placeholder: 'https://yanabiyagroup.com/' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogTitle: '', ogImage: '', keywords: '', canonicalUrl: '' }),
    },
  },

  // ─── ABOUT US ─────────────────────────────────────────────────────────────
  'about-us': {

    'hero': {
      title: 'About Us — Hero Banner',
      description: 'The full-width hero banner at the top of the About Us page.',
      apiKey: 'page-hero-about',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'headline',
      previewImageField: 'image',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', placeholder: 'About Yanabiya Group' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', rows: 2, placeholder: 'Supporting text below the headline' },
        { key: 'image', label: 'Background Image', type: 'image', folder: 'misc' },
        { key: 'breadcrumb', label: 'Breadcrumb Text', type: 'text', half: true, placeholder: 'Home / About Us' },
        { key: 'textAlign', label: 'Text Alignment', type: 'select', half: true, options: [
          { value: 'left', label: 'Left' },
          { value: 'center', label: 'Center' },
        ]},
      ],
      defaultItem: () => ({ id: 'hero', enabled: true, headline: '', subtitle: '', image: '', breadcrumb: '', textAlign: 'left' }),
    },

    'overview': {
      title: 'Company Overview',
      description: 'The main company overview section — proof points, intro text, and highlight cards.',
      apiKey: 'about-page',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'title',
      emptyMessage: 'Add company overview content blocks.',
      fields: [
        { key: 'title', label: 'Section Title', type: 'text', placeholder: 'e.g. Who We Are' },
        { key: 'body', label: 'Body Text', type: 'textarea', rows: 4, placeholder: 'Main paragraph content…' },
        { key: 'image', label: 'Section Image', type: 'image', folder: 'misc' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: 'e.g. 🌍' },
        { key: 'highlight', label: 'Highlight / Callout', type: 'text', half: true, placeholder: 'e.g. 15+ years of excellence' },
      ],
      defaultItem: () => ({ id: `overview-${Date.now()}`, enabled: true, title: '', body: '', image: '', icon: '', highlight: '' }),
    },

    'mission-vision': {
      title: 'Mission, Vision & Values',
      description: 'Mission statement, vision statement, and core company values.',
      apiKey: 'mission-vision',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'title',
      emptyMessage: 'Add mission, vision, or values cards.',
      fields: [
        { key: 'type', label: 'Type', type: 'select', half: true, options: [
          { value: 'mission', label: 'Mission' },
          { value: 'vision', label: 'Vision' },
          { value: 'value', label: 'Core Value' },
        ]},
        { key: 'title', label: 'Title', type: 'text', half: true, placeholder: 'e.g. Our Mission' },
        { key: 'body', label: 'Statement / Description', type: 'textarea', rows: 4, placeholder: 'The full statement…' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: 'e.g. 🎯' },
        { key: 'color', label: 'Accent Color', type: 'color', half: true },
      ],
      defaultItem: () => ({ id: `mv-${Date.now()}`, enabled: true, type: 'mission', title: '', body: '', icon: '', color: '' }),
    },

    'timeline': {
      title: 'Company Timeline',
      description: 'Milestone events in Yanabiya Group\'s history, shown in chronological order.',
      apiKey: 'our-story',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'title',
      emptyMessage: 'Add timeline milestones to tell your company story.',
      fields: [
        { key: 'year', label: 'Year', type: 'text', half: true, placeholder: 'e.g. 2008' },
        { key: 'title', label: 'Milestone Title', type: 'text', half: true, placeholder: 'e.g. Company Founded' },
        { key: 'body', label: 'Description', type: 'textarea', rows: 3, placeholder: 'What happened this year…' },
        { key: 'image', label: 'Milestone Image (optional)', type: 'image', folder: 'misc' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: 'e.g. 🏢' },
        { key: 'highlight', label: 'Highlight Badge', type: 'text', half: true, placeholder: 'e.g. Key Achievement' },
      ],
      defaultItem: () => ({ id: `milestone-${Date.now()}`, enabled: true, year: '', title: '', body: '', image: '', icon: '', highlight: '' }),
    },

    'gallery': {
      title: 'About Us Gallery',
      description: 'Photo gallery shown on the About Us page.',
      apiKey: 'gallery-about',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'caption',
      previewImageField: 'url',
      emptyMessage: 'Upload photos to build your About Us gallery.',
      fields: [
        { key: 'url', label: 'Photo', type: 'image', folder: 'misc' },
        { key: 'caption', label: 'Caption', type: 'text', half: true, placeholder: 'Short description of the photo' },
        { key: 'alt', label: 'Alt Text', type: 'text', half: true, placeholder: 'For accessibility & SEO' },
      ],
      defaultItem: () => ({ id: `photo-${Date.now()}`, enabled: true, url: '', caption: '', alt: '' }),
    },

    'stats': {
      title: 'About Page Statistics',
      description: 'Key achievement numbers shown on the About Us page.',
      apiKey: 'stats-about',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'label',
      emptyMessage: 'Add statistics to highlight your achievements.',
      fields: [
        { key: 'value', label: 'Value', type: 'text', half: true, placeholder: 'e.g. 500+' },
        { key: 'label', label: 'Label', type: 'text', half: true, placeholder: 'e.g. Projects Completed' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: '🏆' },
        { key: 'description', label: 'Description', type: 'text', half: true, placeholder: 'Optional context' },
      ],
      defaultItem: () => ({ id: `stat-${Date.now()}`, enabled: true, value: '', label: '', icon: '', description: '' }),
    },

    'cta': {
      title: 'About Page CTA',
      description: 'Call-to-action block at the bottom of the About Us page.',
      apiKey: 'cta-about',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'headline',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Join Our Team' },
        { key: 'subtext', label: 'Supporting Text', type: 'textarea', rows: 2 },
        { key: 'primaryButtonText', label: 'Button Text', type: 'text', half: true, placeholder: 'Contact Us' },
        { key: 'primaryButtonUrl', label: 'Button URL', type: 'url', half: true, placeholder: '/contact' },
        { key: 'backgroundImage', label: 'Background Image', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: 'cta', enabled: true, headline: '', subtext: '', primaryButtonText: '', primaryButtonUrl: '', backgroundImage: '' }),
    },

    'seo': {
      title: 'SEO Settings — About Us',
      description: 'Meta tags and social sharing settings for the About Us page.',
      apiKey: 'seo-about',
      accent: 'text-emerald-400',
      bgAccent: 'bg-emerald-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'About Us | Yanabiya Group' },
        { key: 'metaDescription', label: 'Meta Description', type: 'textarea', rows: 2 },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords', type: 'tags', placeholder: 'about Yanabiya, company history…' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogImage: '', keywords: '' }),
    },
  },

  // ─── OUR SERVICES ─────────────────────────────────────────────────────────
  'our-services': {

    'hero': {
      title: 'Services Page — Hero Banner',
      description: 'Hero banner shown at the top of service pages.',
      apiKey: 'page-hero-services',
      accent: 'text-violet-400',
      bgAccent: 'bg-violet-400/10',
      previewField: 'headline',
      previewImageField: 'image',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Our Services' },
        { key: 'subtitle', label: 'Subtitle', type: 'textarea', rows: 2 },
        { key: 'image', label: 'Background Image', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: 'hero', enabled: true, headline: '', subtitle: '', image: '' }),
    },

    'faqs': {
      title: 'FAQs',
      description: 'Frequently asked questions about Yanabiya services.',
      apiKey: 'faqs',
      accent: 'text-violet-400',
      bgAccent: 'bg-violet-400/10',
      previewField: 'question',
      emptyMessage: 'Add frequently asked questions about your services.',
      fields: [
        { key: 'question', label: 'Question', type: 'text', placeholder: 'e.g. What services do you offer?' },
        { key: 'answer', label: 'Answer', type: 'textarea', rows: 4, placeholder: 'The full answer…' },
        { key: 'category', label: 'Category (optional)', type: 'text', half: true, placeholder: 'e.g. General' },
        { key: 'order', label: 'Display Order', type: 'number', half: true, placeholder: '1' },
      ],
      defaultItem: () => ({ id: `faq-${Date.now()}`, enabled: true, question: '', answer: '', category: '', order: 0 }),
    },

    'cta': {
      title: 'Services — CTA Sections',
      description: 'Call-to-action blocks on service pages.',
      apiKey: 'cta-services',
      accent: 'text-violet-400',
      bgAccent: 'bg-violet-400/10',
      previewField: 'headline',
      maxItems: 2,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Ready to get started?' },
        { key: 'subtext', label: 'Supporting Text', type: 'textarea', rows: 2 },
        { key: 'primaryButtonText', label: 'Button Text', type: 'text', half: true },
        { key: 'primaryButtonUrl', label: 'Button URL', type: 'url', half: true },
        { key: 'backgroundImage', label: 'Background Image', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: `cta-${Date.now()}`, enabled: true, headline: '', subtext: '', primaryButtonText: '', primaryButtonUrl: '', backgroundImage: '' }),
    },

    'service-cards': {
      title: 'Service Cards',
      description: 'Individual service cards displayed on the services listing page. Each card links to a service detail page.',
      apiKey: 'service-cards',
      accent: 'text-violet-400',
      bgAccent: 'bg-violet-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add service cards to showcase your offerings.',
      fields: [
        { key: 'title', label: 'Service Title', type: 'text', half: true, placeholder: 'e.g. Construction & Engineering' },
        { key: 'tagline', label: 'Tagline', type: 'text', half: true, placeholder: 'Short description for the card' },
        { key: 'body', label: 'Card Body Text', type: 'textarea', rows: 3, placeholder: 'Detailed overview shown on the card' },
        { key: 'image', label: 'Card Image', type: 'image', folder: 'services' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: '🏗️' },
        { key: 'link', label: 'Detail Page URL', type: 'url', half: true, placeholder: '/business/construction' },
        { key: 'buttonText', label: 'Button Label', type: 'text', half: true, placeholder: 'Explore' },
        { key: 'featured', label: 'Featured Card', type: 'toggle' },
        { key: 'color', label: 'Accent Color', type: 'color', half: true },
        { key: 'tag', label: 'Badge / Tag', type: 'text', half: true, placeholder: 'e.g. Popular' },
      ],
      defaultItem: () => ({ id: `card-${Date.now()}`, enabled: true, title: '', tagline: '', body: '', image: '', icon: '', link: '', buttonText: 'Explore', featured: false, color: '', tag: '' }),
    },

    'pricing': {
      title: 'Pricing Plans',
      description: 'Service pricing tiers and packages. Each plan lists its features and a call-to-action.',
      apiKey: 'pricing',
      accent: 'text-violet-400',
      bgAccent: 'bg-violet-400/10',
      previewField: 'name',
      emptyMessage: 'Add pricing plans to showcase your packages.',
      allowDuplicate: true,
      fields: [
        { key: 'name', label: 'Plan Name', type: 'text', half: true, placeholder: 'e.g. Starter' },
        { key: 'price', label: 'Price', type: 'text', half: true, placeholder: 'e.g. $99 or Contact Us' },
        { key: 'period', label: 'Billing Period', type: 'select', half: true, options: [
          { value: '/month', label: 'Per Month' },
          { value: '/year', label: 'Per Year' },
          { value: '/project', label: 'Per Project' },
          { value: 'one-time', label: 'One Time' },
          { value: 'custom', label: 'Custom / Contact' },
        ]},
        { key: 'currency', label: 'Currency', type: 'text', half: true, placeholder: 'e.g. USD or OMR' },
        { key: 'description', label: 'Plan Description', type: 'textarea', rows: 2, placeholder: 'Who this plan is for…' },
        { key: 'features', label: 'Features (one per line)', type: 'textarea', rows: 5, placeholder: 'Feature 1\nFeature 2\nFeature 3' },
        { key: 'buttonText', label: 'CTA Button Text', type: 'text', half: true, placeholder: 'Get Started' },
        { key: 'buttonUrl', label: 'CTA Button URL', type: 'url', half: true, placeholder: '/contact' },
        { key: 'highlighted', label: 'Most Popular / Highlighted', type: 'toggle' },
        { key: 'badge', label: 'Badge Text', type: 'text', half: true, placeholder: 'e.g. Best Value' },
      ],
      defaultItem: () => ({ id: `plan-${Date.now()}`, enabled: true, name: '', price: '', period: '/month', currency: 'USD', description: '', features: '', buttonText: 'Get Started', buttonUrl: '/contact', highlighted: false, badge: '' }),
    },

    'seo': {
      title: 'SEO Settings — Services',
      description: 'Meta tags for service pages.',
      apiKey: 'seo-services',
      accent: 'text-violet-400',
      bgAccent: 'bg-violet-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'Our Services | Yanabiya Group' },
        { key: 'metaDescription', label: 'Meta Description', type: 'textarea', rows: 2 },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords', type: 'tags' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogImage: '', keywords: '' }),
    },
  },

  // ─── OUR GLOBAL BRANCHES ──────────────────────────────────────────────────
  'our-branches': {

    'offices': {
      title: 'Branch Offices',
      description: 'Physical office locations — address, contact details, and photos.',
      apiKey: 'branches',
      accent: 'text-teal-400',
      bgAccent: 'bg-teal-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add your branch office locations.',
      fields: [
        { key: 'name', label: 'Office Name', type: 'text', half: true, placeholder: 'e.g. Oman HQ' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'countryCode', label: 'Country Code', type: 'text', half: true, placeholder: 'e.g. OM' },
        { key: 'flag', label: 'Country Flag Emoji', type: 'text', half: true, placeholder: '🇴🇲' },
        { key: 'address', label: 'Full Address', type: 'textarea', rows: 3 },
        { key: 'phone', label: 'Phone Number', type: 'text', half: true, placeholder: '+968 XXXX XXXX' },
        { key: 'email', label: 'Email Address', type: 'text', half: true, placeholder: 'info@yanabiya.om' },
        { key: 'image', label: 'Office Photo', type: 'image', folder: 'misc' },
        { key: 'mapUrl', label: 'Google Maps URL', type: 'url', placeholder: 'https://maps.google.com/…' },
        { key: 'description', label: 'Office Description', type: 'textarea', rows: 3 },
      ],
      defaultItem: () => ({ id: `office-${Date.now()}`, enabled: true, name: '', country: '', countryCode: '', flag: '', address: '', phone: '', email: '', image: '', mapUrl: '', description: '' }),
    },

    'gallery': {
      title: 'Branches Gallery',
      description: 'Photos representing the company\'s global presence.',
      apiKey: 'gallery-branches',
      accent: 'text-teal-400',
      bgAccent: 'bg-teal-400/10',
      previewField: 'caption',
      previewImageField: 'url',
      emptyMessage: 'Add photos of your international offices.',
      fields: [
        { key: 'url', label: 'Photo', type: 'image', folder: 'misc' },
        { key: 'caption', label: 'Caption', type: 'text', half: true },
        { key: 'alt', label: 'Alt Text', type: 'text', half: true },
        { key: 'location', label: 'Location', type: 'text', half: true, placeholder: 'e.g. Muscat, Oman' },
      ],
      defaultItem: () => ({ id: `photo-${Date.now()}`, enabled: true, url: '', caption: '', alt: '', location: '' }),
    },

    'stats': {
      title: 'Branches Statistics',
      description: 'Global reach statistics — countries, offices, years of operation.',
      apiKey: 'stats-branches',
      accent: 'text-teal-400',
      bgAccent: 'bg-teal-400/10',
      previewField: 'label',
      fields: [
        { key: 'value', label: 'Value', type: 'text', half: true, placeholder: '4+' },
        { key: 'label', label: 'Label', type: 'text', half: true, placeholder: 'Countries' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true },
      ],
      defaultItem: () => ({ id: `stat-${Date.now()}`, enabled: true, value: '', label: '', icon: '' }),
    },

    'maps': {
      title: 'Office Maps',
      description: 'Google Maps embed settings for each branch office location.',
      apiKey: 'maps',
      accent: 'text-teal-400',
      bgAccent: 'bg-teal-400/10',
      previewField: 'locationName',
      emptyMessage: 'Add map embeds for your office locations.',
      fields: [
        { key: 'locationName', label: 'Location Name', type: 'text', half: true, placeholder: 'e.g. Oman Headquarters' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'address', label: 'Full Address', type: 'textarea', rows: 2, placeholder: 'Street, City, Country' },
        { key: 'embedUrl', label: 'Google Maps Embed URL', type: 'url', placeholder: 'https://www.google.com/maps/embed?pb=...' },
        { key: 'lat', label: 'Latitude', type: 'text', half: true, placeholder: 'e.g. 23.5880' },
        { key: 'lng', label: 'Longitude', type: 'text', half: true, placeholder: 'e.g. 58.3829' },
        { key: 'zoom', label: 'Map Zoom Level', type: 'select', half: true, options: [
          { value: '12', label: 'City (12)' },
          { value: '14', label: 'Neighbourhood (14)' },
          { value: '16', label: 'Street (16)' },
          { value: '18', label: 'Building (18)' },
        ]},
        { key: 'markerLabel', label: 'Map Marker Label', type: 'text', half: true, placeholder: 'Yanabiya Group Oman' },
      ],
      defaultItem: () => ({ id: `map-${Date.now()}`, enabled: true, locationName: '', country: '', address: '', embedUrl: '', lat: '', lng: '', zoom: '14', markerLabel: '' }),
    },

    'regional-managers': {
      title: 'Regional Managers',
      description: 'Country and regional manager profiles — the people responsible for each territory.',
      apiKey: 'regional-managers',
      accent: 'text-teal-400',
      bgAccent: 'bg-teal-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add regional manager profiles.',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', half: true, placeholder: 'e.g. Ahmed Al Balushi' },
        { key: 'role', label: 'Role / Title', type: 'text', half: true, placeholder: 'e.g. Country Manager — Oman' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'countryCode', label: 'Country Code', type: 'text', half: true, placeholder: 'e.g. OM' },
        { key: 'flag', label: 'Flag Emoji', type: 'text', half: true, placeholder: '🇴🇲' },
        { key: 'image', label: 'Profile Photo', type: 'image', folder: 'people' },
        { key: 'email', label: 'Email Address', type: 'text', half: true, placeholder: 'manager@yanabiya.om' },
        { key: 'phone', label: 'Phone Number', type: 'text', half: true, placeholder: '+968 XXXX XXXX' },
        { key: 'bio', label: 'Brief Bio', type: 'textarea', rows: 3, placeholder: 'Professional background…' },
        { key: 'linkedin', label: 'LinkedIn URL', type: 'url', half: true },
        { key: 'yearsInRole', label: 'Years in Role', type: 'text', half: true, placeholder: 'e.g. 5+' },
      ],
      defaultItem: () => ({ id: `manager-${Date.now()}`, enabled: true, name: '', role: '', country: '', countryCode: '', flag: '', image: '', email: '', phone: '', bio: '', linkedin: '', yearsInRole: '' }),
    },

    'seo': {
      title: 'SEO — Global Branches',
      description: 'Meta tags for the global branches pages.',
      apiKey: 'seo-branches',
      accent: 'text-teal-400',
      bgAccent: 'bg-teal-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'Our Global Branches | Yanabiya Group' },
        { key: 'metaDescription', label: 'Meta Description', type: 'textarea', rows: 2 },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords', type: 'tags' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogImage: '', keywords: '' }),
    },
  },

  // ─── OUR NETWORK ──────────────────────────────────────────────────────────
  'our-network': {

    'partners': {
      title: 'Partners & Collaborators',
      description: 'Partner organizations, member bodies, and collaborators.',
      apiKey: 'partners',
      accent: 'text-orange-400',
      bgAccent: 'bg-orange-400/10',
      previewField: 'name',
      previewImageField: 'logo',
      emptyMessage: 'Add your partner organizations.',
      fields: [
        { key: 'name', label: 'Partner Name', type: 'text', half: true, placeholder: 'e.g. Oman Chamber of Commerce' },
        { key: 'type', label: 'Type', type: 'select', half: true, options: [
          { value: 'partner', label: 'Partner' },
          { value: 'member', label: 'Member Body' },
          { value: 'client', label: 'Client' },
          { value: 'supplier', label: 'Supplier' },
        ]},
        { key: 'logo', label: 'Logo', type: 'image', folder: 'misc' },
        { key: 'website', label: 'Website URL', type: 'url', half: true, placeholder: 'https://…' },
        { key: 'country', label: 'Country', type: 'text', half: true },
        { key: 'description', label: 'Description', type: 'textarea', rows: 3 },
      ],
      defaultItem: () => ({ id: `partner-${Date.now()}`, enabled: true, name: '', type: 'partner', logo: '', website: '', country: '', description: '' }),
    },

    'network-cards': {
      title: 'Network Cards',
      description: 'Partnership network cards and collaboration descriptions.',
      apiKey: 'network',
      accent: 'text-orange-400',
      bgAccent: 'bg-orange-400/10',
      previewField: 'title',
      emptyMessage: 'Add network partnership cards.',
      fields: [
        { key: 'title', label: 'Title', type: 'text', placeholder: 'e.g. Strategic Alliance' },
        { key: 'body', label: 'Description', type: 'textarea', rows: 3 },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true },
        { key: 'link', label: 'Link URL', type: 'url', half: true },
        { key: 'image', label: 'Card Image', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: `network-${Date.now()}`, enabled: true, title: '', body: '', icon: '', link: '', image: '' }),
    },

    'cta': {
      title: 'Network — CTA Section',
      description: 'Call-to-action for partnership enquiries.',
      apiKey: 'cta-network',
      accent: 'text-orange-400',
      bgAccent: 'bg-orange-400/10',
      previewField: 'headline',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text', placeholder: 'Become a Partner' },
        { key: 'subtext', label: 'Supporting Text', type: 'textarea', rows: 2 },
        { key: 'primaryButtonText', label: 'Button Text', type: 'text', half: true },
        { key: 'primaryButtonUrl', label: 'Button URL', type: 'url', half: true },
        { key: 'backgroundImage', label: 'Background Image', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: 'cta', enabled: true, headline: '', subtext: '', primaryButtonText: '', primaryButtonUrl: '', backgroundImage: '' }),
    },

    'collaborations': {
      title: 'Collaborations',
      description: 'Joint ventures, strategic alliances, and collaboration highlights with partner organizations.',
      apiKey: 'collaborations',
      accent: 'text-orange-400',
      bgAccent: 'bg-orange-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add collaboration highlights to showcase partnerships.',
      fields: [
        { key: 'title', label: 'Collaboration Title', type: 'text', placeholder: 'e.g. Joint Venture with Acme Corp' },
        { key: 'partner', label: 'Partner Organization', type: 'text', half: true, placeholder: 'e.g. Acme Corporation' },
        { key: 'type', label: 'Type', type: 'select', half: true, options: [
          { value: 'joint-venture', label: 'Joint Venture' },
          { value: 'strategic-alliance', label: 'Strategic Alliance' },
          { value: 'mou', label: 'MOU / Agreement' },
          { value: 'partnership', label: 'Partnership' },
          { value: 'sponsorship', label: 'Sponsorship' },
        ]},
        { key: 'year', label: 'Year Established', type: 'text', half: true, placeholder: 'e.g. 2019' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. United Kingdom' },
        { key: 'description', label: 'Description', type: 'textarea', rows: 3, placeholder: 'What this collaboration involves…' },
        { key: 'image', label: 'Image / Banner', type: 'image', folder: 'misc' },
        { key: 'link', label: 'More Info URL', type: 'url', half: true },
        { key: 'status', label: 'Status', type: 'select', half: true, options: [
          { value: 'active', label: 'Active' },
          { value: 'completed', label: 'Completed' },
          { value: 'upcoming', label: 'Upcoming' },
        ]},
      ],
      defaultItem: () => ({ id: `collab-${Date.now()}`, enabled: true, title: '', partner: '', type: 'partnership', year: '', country: '', description: '', image: '', link: '', status: 'active' }),
    },

    'logos': {
      title: 'Partner & Member Logos',
      description: 'Logo grid/carousel showing partner companies, member bodies, and clients. Displayed in the network section.',
      apiKey: 'logos',
      accent: 'text-orange-400',
      bgAccent: 'bg-orange-400/10',
      previewField: 'name',
      previewImageField: 'logo',
      emptyMessage: 'Add partner logos to the network logo wall.',
      fields: [
        { key: 'name', label: 'Organization Name', type: 'text', half: true, placeholder: 'e.g. Oman Chamber of Commerce' },
        { key: 'logo', label: 'Logo Image', type: 'image', folder: 'misc' },
        { key: 'website', label: 'Website URL', type: 'url', half: true, placeholder: 'https://…' },
        { key: 'type', label: 'Category', type: 'select', half: true, options: [
          { value: 'partner', label: 'Partner' },
          { value: 'member', label: 'Member Body' },
          { value: 'client', label: 'Client' },
          { value: 'award', label: 'Award / Certification' },
        ]},
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'description', label: 'Tooltip / Description', type: 'text', placeholder: 'Short description shown on hover' },
      ],
      defaultItem: () => ({ id: `logo-${Date.now()}`, enabled: true, name: '', logo: '', website: '', type: 'partner', country: '', description: '' }),
    },

    'seo': {
      title: 'SEO — Our Network',
      description: 'Meta tags for the network page.',
      apiKey: 'seo-network',
      accent: 'text-orange-400',
      bgAccent: 'bg-orange-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'Our Network | Yanabiya Group' },
        { key: 'metaDescription', label: 'Meta Description', type: 'textarea', rows: 2 },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords', type: 'tags' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogImage: '', keywords: '' }),
    },
  },

  // ─── OUR COMMUNITY ────────────────────────────────────────────────────────
  'our-community': {

    'programs': {
      title: 'Community Programs',
      description: 'Community initiative cards — sustainable growth, community care, etc.',
      apiKey: 'community-hubs',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add community programs and initiatives.',
      fields: [
        { key: 'title', label: 'Program Name', type: 'text', placeholder: 'e.g. Sustainable Growth' },
        { key: 'body', label: 'Description', type: 'textarea', rows: 3 },
        { key: 'image', label: 'Program Image', type: 'image', folder: 'misc' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true },
        { key: 'link', label: 'Page Link', type: 'url', half: true, placeholder: '/community/sustainable-growth' },
        { key: 'tag', label: 'Tag / Badge', type: 'text', half: true, placeholder: 'e.g. Featured' },
      ],
      defaultItem: () => ({ id: `program-${Date.now()}`, enabled: true, title: '', body: '', image: '', icon: '', link: '', tag: '' }),
    },

    'events': {
      title: 'Community Events',
      description: 'Upcoming and past community events and activities.',
      apiKey: 'events',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add community events to showcase your activities.',
      fields: [
        { key: 'title', label: 'Event Name', type: 'text', placeholder: 'Annual Community Day' },
        { key: 'date', label: 'Date', type: 'text', half: true, placeholder: 'e.g. March 15, 2025' },
        { key: 'location', label: 'Location', type: 'text', half: true, placeholder: 'Muscat, Oman' },
        { key: 'description', label: 'Description', type: 'textarea', rows: 3 },
        { key: 'image', label: 'Event Photo', type: 'image', folder: 'misc' },
        { key: 'status', label: 'Status', type: 'select', half: true, options: [
          { value: 'upcoming', label: 'Upcoming' },
          { value: 'past', label: 'Past' },
          { value: 'ongoing', label: 'Ongoing' },
        ]},
        { key: 'registrationUrl', label: 'Registration URL', type: 'url', half: true },
      ],
      defaultItem: () => ({ id: `event-${Date.now()}`, enabled: true, title: '', date: '', location: '', description: '', image: '', status: 'upcoming', registrationUrl: '' }),
    },

    'gallery': {
      title: 'Community Gallery',
      description: 'Photos from community programs and events.',
      apiKey: 'gallery-community',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'caption',
      previewImageField: 'url',
      emptyMessage: 'Upload community photos.',
      fields: [
        { key: 'url', label: 'Photo', type: 'image', folder: 'misc' },
        { key: 'caption', label: 'Caption', type: 'text', half: true },
        { key: 'alt', label: 'Alt Text', type: 'text', half: true },
        { key: 'program', label: 'Related Program', type: 'text', half: true, placeholder: 'e.g. Community Care' },
      ],
      defaultItem: () => ({ id: `photo-${Date.now()}`, enabled: true, url: '', caption: '', alt: '', program: '' }),
    },

    'testimonials': {
      title: 'Community Testimonials',
      description: 'Testimonials from community members and program beneficiaries.',
      apiKey: 'community-testimonials',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add testimonials from community members.',
      fields: [
        { key: 'name', label: 'Name', type: 'text', half: true },
        { key: 'role', label: 'Role / Community', type: 'text', half: true },
        { key: 'review', label: 'Testimonial', type: 'textarea', rows: 4 },
        { key: 'image', label: 'Photo', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: `testimonial-${Date.now()}`, enabled: true, name: '', role: '', review: '', image: '' }),
    },

    'stats': {
      title: 'Community Statistics',
      description: 'Impact numbers — beneficiaries reached, programs run, years active.',
      apiKey: 'stats-community',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'label',
      fields: [
        { key: 'value', label: 'Value', type: 'text', half: true, placeholder: '10,000+' },
        { key: 'label', label: 'Label', type: 'text', half: true, placeholder: 'Beneficiaries Reached' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true },
      ],
      defaultItem: () => ({ id: `stat-${Date.now()}`, enabled: true, value: '', label: '', icon: '' }),
    },

    'cta': {
      title: 'Community — CTA Sections',
      description: 'Get involved / donate call-to-action blocks.',
      apiKey: 'cta-community',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'headline',
      maxItems: 2,
      fields: [
        { key: 'headline', label: 'Headline', type: 'text' },
        { key: 'subtext', label: 'Supporting Text', type: 'textarea', rows: 2 },
        { key: 'primaryButtonText', label: 'Button Text', type: 'text', half: true },
        { key: 'primaryButtonUrl', label: 'Button URL', type: 'url', half: true },
        { key: 'backgroundImage', label: 'Background Image', type: 'image', folder: 'misc' },
      ],
      defaultItem: () => ({ id: `cta-${Date.now()}`, enabled: true, headline: '', subtext: '', primaryButtonText: '', primaryButtonUrl: '', backgroundImage: '' }),
    },

    'seo': {
      title: 'SEO — Our Community',
      description: 'Meta tags for community pages.',
      apiKey: 'seo-community',
      accent: 'text-rose-400',
      bgAccent: 'bg-rose-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'Our Community | Yanabiya Group' },
        { key: 'metaDescription', label: 'Meta Description', type: 'textarea', rows: 2 },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords', type: 'tags' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogImage: '', keywords: '' }),
    },
  },

  // ─── OUR PEOPLE ───────────────────────────────────────────────────────────
  'our-people': {

    'leadership': {
      title: 'Leadership Team',
      description: 'Board members, CEO, vice-chairman, and executive leadership profiles.',
      apiKey: 'leadership',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add leadership profiles.',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', half: true, placeholder: 'e.g. Mohammed Al Rashidi' },
        { key: 'role', label: 'Title / Role', type: 'text', half: true, placeholder: 'e.g. Chief Executive Officer' },
        { key: 'bio', label: 'Biography', type: 'textarea', rows: 5, placeholder: 'Professional background and achievements…' },
        { key: 'image', label: 'Profile Photo', type: 'image', folder: 'people' },
        { key: 'nationality', label: 'Nationality / Country', type: 'text', half: true },
        { key: 'linkedin', label: 'LinkedIn URL', type: 'url', half: true },
        { key: 'level', label: 'Level', type: 'select', half: true, options: [
          { value: 'chairman', label: 'Chairman / Vice Chairman' },
          { value: 'ceo', label: 'CEO' },
          { value: 'board', label: 'Board Member' },
          { value: 'executive', label: 'Executive' },
          { value: 'manager', label: 'Manager' },
        ]},
        { key: 'order', label: 'Display Order', type: 'number', half: true, placeholder: '1' },
      ],
      defaultItem: () => ({ id: `leader-${Date.now()}`, enabled: true, name: '', role: '', bio: '', image: '', nationality: '', linkedin: '', level: 'executive', order: 0 }),
    },

    'team': {
      title: 'Team Members',
      description: 'All team member profiles across all departments and countries.',
      apiKey: 'people',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add team member profiles.',
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', half: true },
        { key: 'role', label: 'Role / Job Title', type: 'text', half: true },
        { key: 'department', label: 'Department', type: 'text', half: true, placeholder: 'e.g. Finance' },
        { key: 'country', label: 'Country / Office', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'image', label: 'Profile Photo', type: 'image', folder: 'people' },
        { key: 'bio', label: 'Short Bio (optional)', type: 'textarea', rows: 3 },
        { key: 'email', label: 'Email', type: 'text', half: true },
        { key: 'linkedin', label: 'LinkedIn URL', type: 'url', half: true },
      ],
      defaultItem: () => ({ id: `member-${Date.now()}`, enabled: true, name: '', role: '', department: '', country: '', image: '', bio: '', email: '', linkedin: '' }),
    },

    'gallery': {
      title: 'People Gallery',
      description: 'Team and workplace photos.',
      apiKey: 'gallery-people',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'caption',
      previewImageField: 'url',
      emptyMessage: 'Upload team and workplace photos.',
      fields: [
        { key: 'url', label: 'Photo', type: 'image', folder: 'people' },
        { key: 'caption', label: 'Caption', type: 'text', half: true },
        { key: 'alt', label: 'Alt Text', type: 'text', half: true },
      ],
      defaultItem: () => ({ id: `photo-${Date.now()}`, enabled: true, url: '', caption: '', alt: '' }),
    },

    'departments': {
      title: 'Departments',
      description: 'Company department structure — each department with its head, description, and country presence.',
      apiKey: 'departments',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'name',
      emptyMessage: 'Add departments to show your organizational structure.',
      fields: [
        { key: 'name', label: 'Department Name', type: 'text', half: true, placeholder: 'e.g. Finance & Accounts' },
        { key: 'head', label: 'Department Head', type: 'text', half: true, placeholder: 'e.g. Mohammed Al Hassan' },
        { key: 'description', label: 'Department Description', type: 'textarea', rows: 3, placeholder: 'What this department does…' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: '💼' },
        { key: 'countries', label: 'Countries (comma-separated)', type: 'text', half: true, placeholder: 'e.g. Oman, UK, Bangladesh' },
        { key: 'employeeCount', label: 'Employee Count', type: 'text', half: true, placeholder: 'e.g. 12' },
        { key: 'image', label: 'Department Image', type: 'image', folder: 'misc' },
        { key: 'email', label: 'Department Email', type: 'text', half: true, placeholder: 'dept@yanabiya.om' },
        { key: 'responsibilities', label: 'Key Responsibilities (one per line)', type: 'textarea', rows: 4, placeholder: 'Responsibility 1\nResponsibility 2' },
      ],
      defaultItem: () => ({ id: `dept-${Date.now()}`, enabled: true, name: '', head: '', description: '', icon: '', countries: '', employeeCount: '', image: '', email: '', responsibilities: '' }),
    },

    'employee-cards': {
      title: 'Employee Cards',
      description: 'Featured employee profile cards — styled cards for highlighted team members shown on the people pages.',
      apiKey: 'employee-cards',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'name',
      previewImageField: 'image',
      emptyMessage: 'Add featured employee cards.',
      allowDuplicate: false,
      fields: [
        { key: 'name', label: 'Full Name', type: 'text', half: true, placeholder: 'e.g. Sara Al Busaidi' },
        { key: 'role', label: 'Job Title', type: 'text', half: true, placeholder: 'e.g. Senior Manager' },
        { key: 'department', label: 'Department', type: 'text', half: true, placeholder: 'e.g. Operations' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'image', label: 'Profile Photo', type: 'image', folder: 'people' },
        { key: 'quote', label: 'Personal Quote', type: 'textarea', rows: 2, placeholder: '"A short inspiring quote from this employee"' },
        { key: 'bio', label: 'Short Bio', type: 'textarea', rows: 3, placeholder: 'Brief professional background…' },
        { key: 'email', label: 'Email', type: 'text', half: true },
        { key: 'linkedin', label: 'LinkedIn URL', type: 'url', half: true },
        { key: 'yearsAtCompany', label: 'Years at Company', type: 'text', half: true, placeholder: 'e.g. 7' },
        { key: 'cardStyle', label: 'Card Style', type: 'select', half: true, options: [
          { value: 'standard', label: 'Standard' },
          { value: 'featured', label: 'Featured (larger)' },
          { value: 'minimal', label: 'Minimal' },
        ]},
      ],
      defaultItem: () => ({ id: `emp-${Date.now()}`, enabled: true, name: '', role: '', department: '', country: '', image: '', quote: '', bio: '', email: '', linkedin: '', yearsAtCompany: '', cardStyle: 'standard' }),
    },

    'achievements': {
      title: 'Achievements & Awards',
      description: 'Company awards, certifications, recognitions, and milestones. Displayed to build credibility.',
      apiKey: 'achievements',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'title',
      previewImageField: 'image',
      emptyMessage: 'Add awards and achievements to showcase your credentials.',
      allowDuplicate: true,
      fields: [
        { key: 'title', label: 'Achievement Title', type: 'text', placeholder: 'e.g. Best Employer Award 2024' },
        { key: 'type', label: 'Type', type: 'select', half: true, options: [
          { value: 'award', label: 'Award' },
          { value: 'certification', label: 'Certification' },
          { value: 'recognition', label: 'Recognition' },
          { value: 'milestone', label: 'Company Milestone' },
          { value: 'accreditation', label: 'Accreditation' },
        ]},
        { key: 'year', label: 'Year', type: 'text', half: true, placeholder: 'e.g. 2024' },
        { key: 'issuer', label: 'Issued By', type: 'text', half: true, placeholder: 'e.g. Oman Ministry of Commerce' },
        { key: 'country', label: 'Country', type: 'text', half: true, placeholder: 'e.g. Oman' },
        { key: 'description', label: 'Description', type: 'textarea', rows: 3, placeholder: 'What this award represents and why it was received…' },
        { key: 'image', label: 'Award Image / Certificate', type: 'image', folder: 'misc' },
        { key: 'link', label: 'Reference URL', type: 'url', half: true, placeholder: 'https://…' },
        { key: 'icon', label: 'Icon Emoji', type: 'text', half: true, placeholder: '🏆' },
      ],
      defaultItem: () => ({ id: `achievement-${Date.now()}`, enabled: true, title: '', type: 'award', year: '', issuer: '', country: '', description: '', image: '', link: '', icon: '🏆' }),
    },

    'seo': {
      title: 'SEO — Our People',
      description: 'Meta tags for people pages.',
      apiKey: 'seo-people',
      accent: 'text-amber-400',
      bgAccent: 'bg-amber-400/10',
      previewField: 'pageTitle',
      maxItems: 1,
      allowDuplicate: false,
      fields: [
        { key: 'pageTitle', label: 'Page Title', type: 'text', placeholder: 'Our People | Yanabiya Group' },
        { key: 'metaDescription', label: 'Meta Description', type: 'textarea', rows: 2 },
        { key: 'ogImage', label: 'Social Share Image', type: 'image', folder: 'misc' },
        { key: 'keywords', label: 'Keywords', type: 'tags' },
      ],
      defaultItem: () => ({ id: 'seo', enabled: true, pageTitle: '', metaDescription: '', ogImage: '', keywords: '' }),
    },
  },
}
